package com.example.demo.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents the Product entity in the database.
 *
 * @Entity: Marks this class as a JPA entity, meaning it maps to a database table.
 * @Table: Specifies the name of the database table if it's different from the class name.
 * @Data: A Lombok annotation that bundles @ToString, @EqualsAndHashCode, @Getter, @Setter, and @RequiredArgsConstructor.
 *        It automatically generates getters, setters, toString(), equals(), and hashCode() methods.
 * @NoArgsConstructor: A Lombok annotation that generates a constructor with no arguments.
 * @AllArgsConstructor: A Lombok annotation that generates a constructor with all arguments.
 */
@Entity
@Table(name = "products")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Product {

    /**
     * Unique identifier for the product.
     * @Id: Marks this field as the primary key of the entity.
     * @GeneratedValue: Specifies the strategy for primary key generation.
     *   - GenerationType.IDENTITY: Indicates that the persistence provider must assign primary keys
     *     for the entity using a database identity column.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the product.
     * @Column: Specifies the mapped column for the persistent property or field.
     *   - nullable = false: Indicates that the column cannot contain null values.
     *   - unique = true: Indicates that the column must have unique values (for product name, this might be optional
     *     or based on business rules, but good for demonstration).
     */
    @Column(nullable = false, unique = true)
    private String name;

    /**
     * Description of the product.
     * @Column: Allows defining properties of the column like length.
     */
    @Column(length = 500)
    private String description;

    /**
     * Price of the product.
     * @Column: Allows defining properties of the column like precision and scale for decimal numbers.
     */
    @Column(nullable = false, precision = 10, scale = 2)
    private Double price;

    /**
     * Default constructor (required by JPA for proxy creation, but also generated by Lombok's @NoArgsConstructor).
     */
    // You can remove this explicit constructor if using Lombok's @NoArgsConstructor
    // public Product() {
    // }

    /**
     * Constructor for creating a new product without an ID (ID will be generated by the database).
     */
    public Product(String name, String description, Double price) {
        this.name = name;
        this.description = description;
        this.price = price;
    }
}
