package com.example.demo.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity // Marks this class as a JPA entity, mapped to a database table
@Data // Lombok annotation: Generates getters, setters, toString, equals, and hashCode methods
@NoArgsConstructor // Lombok annotation: Generates a no-argument constructor
@AllArgsConstructor // Lombok annotation: Generates a constructor with all fields as arguments
public class Product {

    @Id // Marks this field as the primary key of the entity
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Configures the primary key to be auto-generated by the database
    private Long id;
    private String name;
    private double price;
    private String description;

    // We can add a custom constructor if needed, or rely on Lombok's @NoArgsConstructor/@AllArgsConstructor
    // public Product(String name, double price, String description) {
    //     this.name = name;
    //     this.price = price;
    //     this.description = description;
    // }
}
