package com.example.restapi.service;

import com.example.restapi.dto.ProductRequestDTO;
import com.example.restapi.dto.ProductResponseDTO;
import com.example.restapi.exception.ResourceNotFoundException;
import com.example.restapi.model.Product;
import com.example.restapi.repository.ProductRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.stream.Collectors;

/**
 * Service layer for managing Product-related business logic.
 * Handles operations like creating, retrieving, updating, and deleting products.
 *
 * @Service: Marks this class as a Spring Service component, making it eligible
 *           for Spring's component scanning and dependency injection.
 * @RequiredArgsConstructor: Lombok annotation that generates a constructor with
 *                           required arguments (final fields), enabling constructor injection.
 */
@Service
@RequiredArgsConstructor
public class ProductService {

    private final ProductRepository productRepository; // Injected via constructor by Lombok

    /**
     * Retrieves all products.
     * @return A list of ProductResponseDTOs.
     */
    public List<ProductResponseDTO> getAllProducts() {
        return productRepository.findAll().stream()
                .map(this::mapToDTO) // Map each Product entity to a ProductResponseDTO
                .collect(Collectors.toList());
    }

    /**
     * Retrieves a product by its ID.
     * @param id The ID of the product to retrieve.
     * @return The ProductResponseDTO if found.
     * @throws ResourceNotFoundException If no product is found with the given ID.
     */
    public ProductResponseDTO getProductById(Long id) {
        Product product = productRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Product not found with id: " + id));
        return mapToDTO(product);
    }

    /**
     * Creates a new product.
     * @param productRequestDTO The DTO containing product creation data.
     * @return The ProductResponseDTO of the newly created product.
     */
    public ProductResponseDTO createProduct(ProductRequestDTO productRequestDTO) {
        Product product = mapToEntity(productRequestDTO); // Convert DTO to Entity
        Product savedProduct = productRepository.save(product); // Save to database
        return mapToDTO(savedProduct); // Convert saved Entity back to DTO for response
    }

    /**
     * Updates an existing product.
     * @param id The ID of the product to update.
     * @param productRequestDTO The DTO containing updated product data.
     * @return The ProductResponseDTO of the updated product.
     * @throws ResourceNotFoundException If no product is found with the given ID.
     */
    public ProductResponseDTO updateProduct(Long id, ProductRequestDTO productRequestDTO) {
        Product existingProduct = productRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Product not found with id: " + id));

        // Update fields from DTO to existing entity
        existingProduct.setName(productRequestDTO.getName());
        existingProduct.setDescription(productRequestDTO.getDescription());
        existingProduct.setPrice(productRequestDTO.getPrice());

        Product updatedProduct = productRepository.save(existingProduct); // Save the updated entity
        return mapToDTO(updatedProduct);
    }

    /**
     * Deletes a product by its ID.
     * @param id The ID of the product to delete.
     * @throws ResourceNotFoundException If no product is found with the given ID.
     */
    public void deleteProduct(Long id) {
        if (!productRepository.existsById(id)) {
            throw new ResourceNotFoundException("Product not found with id: " + id);
        }
        productRepository.deleteById(id);
    }

    /**
     * Helper method to convert Product entity to ProductResponseDTO.
     * @param product The Product entity.
     * @return The corresponding ProductResponseDTO.
     */
    private ProductResponseDTO mapToDTO(Product product) {
        return new ProductResponseDTO(product.getId(), product.getName(), product.getDescription(), product.getPrice());
    }

    /**
     * Helper method to convert ProductRequestDTO to Product entity.
     * Note: ID is not set here as it's generated by the database.
     * @param productRequestDTO The ProductRequestDTO.
     * @return The corresponding Product entity.
     */
    private Product mapToEntity(ProductRequestDTO productRequestDTO) {
        return new Product(null, productRequestDTO.getName(), productRequestDTO.getDescription(), productRequestDTO.getPrice());
    }
}
