package com.example.productapi.service;

import com.example.productapi.dto.ProductDTO;
import com.example.productapi.model.Product;
import com.example.productapi.repository.ProductRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

/**
 * Service layer for managing Product-related business logic.
 * Interacts with the ProductRepository for data access and handles mapping
 * between Product entities and ProductDTOs.
 */
@Service // Marks this class as a Spring service component. Service classes encapsulate business logic.
public class ProductService {

    private final ProductRepository productRepository;

    // Dependency Injection: Spring automatically injects an instance of ProductRepository
    public ProductService(ProductRepository productRepository) {
        this.productRepository = productRepository;
    }

    /**
     * Retrieves all products and maps them to DTOs.
     * @return A list of ProductDTOs.
     */
    public List<ProductDTO> getAllProducts() {
        return productRepository.findAll().stream()
                .map(this::convertToDto) // Map each Product entity to a ProductDTO
                .collect(Collectors.toList());
    }

    /**
     * Retrieves a product by its ID and maps it to a DTO.
     * @param id The ID of the product.
     * @return An Optional containing the ProductDTO if found, otherwise empty.
     */
    public Optional<ProductDTO> getProductById(Long id) {
        return productRepository.findById(id)
                .map(this::convertToDto); // Map the found Product entity to a ProductDTO
    }

    /**
     * Creates a new product from a DTO.
     * @param productDTO The DTO containing product data.
     * @return The created ProductDTO with the generated ID.
     */
    @Transactional // Ensures the entire method executes within a single database transaction.
                   // If an exception occurs, the transaction will be rolled back.
    public ProductDTO createProduct(ProductDTO productDTO) {
        Product product = convertToEntity(productDTO); // Convert DTO to entity
        Product savedProduct = productRepository.save(product); // Persist entity
        return convertToDto(savedProduct); // Convert saved entity back to DTO for response
    }

    /**
     * Updates an existing product.
     * @param id The ID of the product to update.
     * @param productDTO The DTO with updated product data.
     * @return An Optional containing the updated ProductDTO if found, otherwise empty.
     */
    @Transactional
    public Optional<ProductDTO> updateProduct(Long id, ProductDTO productDTO) {
        return productRepository.findById(id)
                .map(existingProduct -> {
                    // Update fields of the existing product entity
                    existingProduct.setName(productDTO.getName());
                    existingProduct.setDescription(productDTO.getDescription());
                    existingProduct.setPrice(productDTO.getPrice());
                    existingProduct.setQuantity(productDTO.getQuantity());
                    Product updatedProduct = productRepository.save(existingProduct); // save() also handles updates for existing entities
                    return convertToDto(updatedProduct);
                });
    }

    /**
     * Deletes a product by its ID.
     * @param id The ID of the product to delete.
     * @return true if the product was found and deleted, false otherwise.
     */
    @Transactional
    public boolean deleteProduct(Long id) {
        return productRepository.findById(id)
                .map(product -> {
                    productRepository.delete(product); // Delete the found product
                    return true; // Return true as deletion was successful
                }).orElse(false); // If product not found, return false
    }

    /**
     * Converts a Product entity to a ProductDTO.
     * This helper method encapsulates the mapping logic.
     * @param product The Product entity.
     * @return The corresponding ProductDTO.
     */
    private ProductDTO convertToDto(Product product) {
        return new ProductDTO(
                product.getId(),
                product.getName(),
                product.getDescription(),
                product.getPrice(),
                product.getQuantity()
        );
    }

    /**
     * Converts a ProductDTO to a Product entity.
     * Note: ID is not set from DTO as it's typically auto-generated by the database for new entities.
     * For updates, the ID would be retrieved from the path variable and set on the existing entity
     * (as seen in updateProduct method).
     * @param productDTO The ProductDTO.
     * @return The corresponding Product entity.
     */
    private Product convertToEntity(ProductDTO productDTO) {
        Product product = new Product();
        product.setName(productDTO.getName());
        product.setDescription(productDTO.getDescription());
        product.setPrice(productDTO.getPrice());
        product.setQuantity(productDTO.getQuantity());
        return product;
    }
}
