from django.urls import reverse
from rest_framework import status
from rest_framework.test import APITestCase, APIClient
from myapp.models import Product
from myapp.serializers import ProductSerializer
from decimal import Decimal

class ProductAPITest(APITestCase):
    """
    Tests for the Product API endpoints using ProductViewSet.
    """
    def setUp(self):
        """
        Set up an API client and some initial product data for tests.
        """
        self.client = APIClient()
        self.product1 = Product.objects.create(
            name="Test Product 1",
            description="Description for Test Product 1",
            price=Decimal('100.00'),
            stock=10
        )
        self.product2 = Product.objects.create(
            name="Test Product 2",
            description="Description for Test Product 2",
            price=Decimal('200.00'),
            stock=0
        )
        self.list_url = reverse('product-list') # 'product-list' is generated by DefaultRouter for ProductViewSet
        self.detail_url = reverse('product-detail', kwargs={'pk': self.product1.id}) # 'product-detail'

    def test_get_product_list(self):
        """
        Ensure we can retrieve a list of products.
        """
        response = self.client.get(self.list_url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        # Check that both products are in the response
        self.assertEqual(len(response.data['results']), 2) # DefaultRouter often adds pagination
        serializer = ProductSerializer(Product.objects.all().order_by('name'), many=True)
        # Compare sorted serialized data, especially useful with pagination
        self.assertEqual(response.data['results'], serializer.data)

    def test_get_single_product(self):
        """
        Ensure we can retrieve a single product by ID.
        """
        response = self.client.get(self.detail_url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        serializer = ProductSerializer(self.product1)
        self.assertEqual(response.data, serializer.data)

    def test_create_product(self):
        """
        Ensure we can create a new product.
        """
        data = {
            "name": "New Product",
            "description": "A brand new product.",
            "price": Decimal('50.00'),
            "stock": 5
        }
        response = self.client.post(self.list_url, data, format='json')
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(Product.objects.count(), 3) # Two initial + one new
        self.assertEqual(Product.objects.get(name="New Product").stock, 5)

    def test_create_product_invalid_data(self):
        """
        Ensure we cannot create a product with invalid data (e.g., negative price).
        """
        data = {
            "name": "Invalid Product",
            "description": "Product with invalid price.",
            "price": Decimal('-10.00'), # Invalid price
            "stock": 10
        }
        response = self.client.post(self.list_url, data, format='json')
        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertIn('price', response.data)
        self.assertEqual(Product.objects.count(), 2) # No new product created

    def test_update_product(self):
        """
        Ensure we can update an existing product.
        """
        update_data = {
            "name": "Updated Product Name",
            "price": Decimal('120.00'),
            "stock": 15
        }
        response = self.client.put(self.detail_url, update_data, format='json')
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.product1.refresh_from_db() # Reload product data from the database
        self.assertEqual(self.product1.name, "Updated Product Name")
        self.assertEqual(self.product1.price, Decimal('120.00'))
        self.assertEqual(self.product1.stock, 15)

    def test_partial_update_product(self):
        """
        Ensure we can partially update an existing product using PATCH.
        """
        partial_update_data = {
            "stock": 8
        }
        response = self.client.patch(self.detail_url, partial_update_data, format='json')
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.product1.refresh_from_db()
        self.assertEqual(self.product1.stock, 8)
        self.assertEqual(self.product1.name, "Test Product 1") # Name should remain unchanged

    def test_delete_product(self):
        """
        Ensure we can delete a product.
        """
        response = self.client.delete(self.detail_url)
        self.assertEqual(response.status_code, status.HTTP_204_NO_CONTENT)
        self.assertEqual(Product.objects.count(), 1) # Only product2 remains
        with self.assertRaises(Product.DoesNotExist):
            Product.objects.get(id=self.product1.id)
