from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import ItemViewSet

# Create a router and register our viewsets with it.
# DefaultRouter automatically generates URL patterns for standard ModelViewSet actions.
router = DefaultRouter()
# Register the ItemViewSet.
# The first argument is the URL prefix ('items/').
# The second argument is the ViewSet class.
# 'basename' is used to generate URL names (e.g., 'item-list', 'item-detail').
# It's crucial if you don't define a 'queryset' attribute on your ViewSet.
router.register(r'items', ItemViewSet, basename='item')

# The API URLs are now determined automatically by the router.
# This app-level urlpatterns list includes all the URLs generated by the router.
urlpatterns = [
    path('', include(router.urls)), # Include all router-generated URLs under the 'api/' prefix from project urls.
]
