package com.example.restapi.dto;

import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Data Transfer Object (DTO) for Product.
 * Used for receiving product data from API requests (e.g., POST, PUT).
 * It typically excludes the 'id' field as it's generated by the database for new products.
 *
 * {@code @Data}, {@code @NoArgsConstructor}, {@code @AllArgsConstructor} (Lombok) for boilerplate.
 * Validation annotations (e.g., {@code @NotBlank}, {@code @NotNull}, {@code @DecimalMin})
 * ensure data integrity before processing.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class ProductDTO {

    /**
     * The name of the product. Cannot be null or empty.
     */
    @NotBlank(message = "Product name is required")
    @Size(min = 2, max = 100, message = "Product name must be between 2 and 100 characters")
    private String name;

    /**
     * A description of the product. Optional, but has a size constraint if provided.
     */
    @Size(max = 500, message = "Product description cannot exceed 500 characters")
    private String description;

    /**
     * The price of the product. Cannot be null and must be a positive number.
     */
    @NotNull(message = "Product price is required")
    @DecimalMin(value = "0.01", message = "Product price must be greater than 0")
    private Double price;
}
